# Generated by Django 4.1.7 on 2023-03-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marca',
            new_name='Marcas',
        ),
    ]
